[project]
name = "pyrenote-desk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mutagen>=1.47.0",
    "numpy==1.26.4",
    "pandas>=2.3.2",
    "torch-utils>=0.1.2",
]
